buildscript {
    repositories {
        mavenCentral()
        maven {
            name = 'forge'
            url = 'https://maven.minecraftforge.net'
        }
    }
    dependencies {
        classpath('com.anatawa12.forge:ForgeGradle:2.3-1.0.+') {
            changing = true
        }
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'

group = mod_group_id
version = mod_version
archivesBaseName = "${mod_name}-${minecraft_version}"

sourceCompatibility = targetCompatibility = '1.8'
compileJava {
    sourceCompatibility = targetCompatibility = '1.8'
    options.encoding = 'UTF-8'
}

minecraft {
    version = "${minecraft_version}-${forge_version}"
    runDir = 'run'
    mappings = mappings_version
    makeObfSourceJar = false
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mcversion', minecraft_version

    filesMatching('mcmod.info') {
        expand 'version': project.version,
                'mcversion': minecraft_version,
                'mod_id': mod_id,
                'mod_name': mod_name,
                'mod_authors': mod_authors,
                'mod_description': mod_description
    }
}

jar {
    manifest {
        attributes([
                'Specification-Title'  : mod_id,
                'Specification-Vendor' : mod_authors,
                'Specification-Version': '1',
                'Implementation-Title' : project.name,
                'Implementation-Version': project.version
        ])
    }
}
